@azureHostBaseUrl = https://<func site>>.azurewebsites.net

// generate endpoint
POST {{azureHostBaseUrl}}/convert
Content-Type: application/json
x-functions-key: <app key>

{
   "values": [
        {
            "recordId": "0",
            "data": {
                "text": "Here is a table: <table>\n<tr>\n<th>ZIP Code</th>\n<th>USPS ZIP Code Name</th>\n<th>Territory</th>\n</tr>\n<tr>\n<td>98001</td>\n<td>Auburn</td>\n<td>1</td>\n</tr>\n</table>"
            }
        }
    ]
}