@localHostBaseUrl = http://localhost:7071

// convert-table endpoint
POST {{localHostBaseUrl}}/convert
Content-Type: application/json
x-functions-key: TODO ADD

{
   "values": [
        {
            "recordId": "0",
            "data": {
                "text": "Here is a table: <table>\n<tr>\n<th>ZIP Code</th>\n<th>USPS ZIP Code Name</th>\n<th>Territory</th>\n</tr>\n<tr>\n<td>98001</td>\n<td>Auburn</td>\n<td>1</td>\n</tr>\n</table>"
                }
        }
    ]
}